Remove dash from storage account name
Otherwise Azure breaks deployment with message:

Error: azurerm_storage_account.provider: name can only consist of
lowercase letters and numbers, and must be between 3 and 24 characters
long