Setup Azure Storage with Terraform (#2)
* Setup Azure Storage with Terraform

* Fix a typo in the description

* Rename container to more generic name

* Add azure-storage dependency

* Configure Azure Storage

* Add BlobContainerInfoContributor

* Add smoke test for storage container

* Log warning when StorageException is thrown

* Correct PRODUCT_NAME value to rpe

This follows our CNP-related naming standards where all our products are
branded as "rpe".

* Fix reference to the mainClassName

* Rename result jar file to include project name

* Add files required during deployment

AppInsights added as a bonus.

* Pass infrastructure parameters down to the app

* Differentiate storage accounts between environments

Each environment should have its own account and storage.

* Remove dash from storage account name

Otherwise Azure breaks deployment with message:

Error: azurerm_storage_account.provider: name can only consist of
lowercase letters and numbers, and must be between 3 and 24 characters
long

* Enable slack notifications

* Upgrade azure-storage library to 7.0.0

* Remove unnecessary .tfvars files

They may return when necessary.

* Fix build info set by Jenkins

* Remove bit excessive asp_name variable

Pipeline already sets the value for us.

Besides that, the convention is ${product}-${env}-asp